[project]
name = "zameen-scraper"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-openrouter>=0.2.8",
    "langgraph>=1.2.11",
    "langsmith>=0.12.1",
    "openevals>=0.2.0",
    "pandas>=3.0.5",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "langgraph-cli[inmem]>=0.4.31",
    "pyflakes>=3.4.0",
]
