"""Location tree and alias generation — fully automatic, no hand curation.

The tree comes from Zameen's own breadcrumb location ids, so places have
stable integer identity. That alone fixes the "Askari 5 - Sector J" vs
"Askari 5 - Sector J Flats" split: same id 17289, so the text is just a label.

Aliases are generated by rule plus a small fixed abbreviation dictionary.
An A/B test showed LLM-generated aliases add nothing over this (both 12/13 on
realistic queries), so no model is involved here.
"""

from __future__ import annotations

import re
import unicodedata

# Words that carry no identity on their own. "2 bed in bahria town" once
# matched Gadap Town at 1.00 purely because both contain "town".
GENERIC = {
    "town", "city", "phase", "block", "sector", "road", "society",
    "complex", "housing", "scheme", "cooperative", "karachi", "new", "old", "area",
}

# Not derivable by prefix or substring: "cantt" is not a prefix of
# "cantonment". Fixed size — domain vocabulary, not a per-location list.
ABBR = {
    "cantonment": ["cantt", "cant"],
    "society": ["soc"],
    "cooperative": ["coop"],
}

_TYPE_SUFFIX = re.compile(
    r"\s+(Houses|Flats|Homes|Residential Plots|Commercial Plots|Plots|Property|Apartments)$",
    re.IGNORECASE,
)
_LISTING_LEAF = re.compile(
    r"^(Residential Plot|Commercial Plot|House|Flat|Plot|Upper Portion|Lower Portion)\s+\d{6,}$",
    re.IGNORECASE,
)


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s or "").encode("ascii", "ignore").decode()
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", s.lower())).strip()


def strip_type(name: str) -> str:
    prev = None
    while prev != name:
        prev = name
        name = _TYPE_SUFFIX.sub("", name).strip()
    return name


def build_tree(listings: list[dict]) -> dict[int, dict]:
    """Assemble {location_id: node} from breadcrumb chains across all records."""
    nodes: dict[int, dict] = {}
    for rec in listings:
        items = (rec.get("structuredData") or [{}])[0].get("itemListElement") or []
        chain: list[dict] = []
        for it in items:
            if not it.get("item"):
                continue
            m = re.search(r"-(\d+)-\d+\.html$", it["item"])
            if not m:
                continue
            name = strip_type(it.get("name") or "")
            if not name or _LISTING_LEAF.match(name):
                continue
            chain.append({"id": int(m.group(1)), "name": name})

        # The listing URL's trailing id is the authoritative leaf.
        m = re.search(r"-(\d+)-(\d+)-\d+\.html$", rec.get("url", ""))
        if m:
            leaf_id = int(m.group(2))
            if not any(c["id"] == leaf_id for c in chain):
                raw = [
                    strip_type(n)
                    for n in (rec.get("facts", {}).get("locationHierarchy") or [])
                ]
                raw = [n for n in raw if n and not _LISTING_LEAF.match(n)]
                if raw:
                    chain.append({"id": leaf_id, "name": raw[-1]})

        for i, c in enumerate(chain):
            path = ".".join(str(x["id"]) for x in chain[: i + 1])
            prev = nodes.get(c["id"])
            # Keep the deepest/most-qualified path seen for this node.
            if prev is None or len(path) > len(prev["path"]):
                nodes[c["id"]] = {
                    "id": c["id"],
                    "name": c["name"],
                    "parent_id": chain[i - 1]["id"] if i else None,
                    "path": path,
                    "depth": i,
                }
    return nodes


def _rule_aliases(node: dict, nodes: dict[int, dict]) -> set[str]:
    out: set[str] = set()

    def add(s: str) -> None:
        n = norm(s)
        if len(n) <= 2:
            return
        if all(w in GENERIC for w in n.split()):
            return          # guard 1: never an all-generic alias
        out.add(n)

    name = node["name"]
    add(name)
    add(name.replace("-", " "))
    add(re.sub(r"\s*-\s*e\s*-\s*", " ", name, flags=re.I))
    add(re.sub(r"\s*-\s*e\s*-\s*", " e ", name, flags=re.I))
    add(re.sub(r"[\s-]", "", name))

    # "Askari 6" -> ask 6 / aska 6 / askar 6.  A real listing is titled "…in Ask 6".
    m = re.match(r"^([a-z]{4,})\s+(\d+[a-z]?)$", norm(name))
    if m:
        for k in range(3, len(m.group(1))):
            add(f"{m.group(1)[:k]} {m.group(2)}")

    parent = nodes.get(node["parent_id"]) if node.get("parent_id") else None
    if parent:
        pn, nn = norm(parent["name"]), norm(name)
        if pn not in nn:
            add(f"{nn} {pn}")
            add(f"{pn} {nn}")
        # Only a spaced dash marks a real tail ("Askari 5 - Sector J"),
        # never the "-e-" infix in "Gulshan-e-Iqbal".
        if re.search(r"\s-\s", name):
            tail = " ".join(re.split(r"\s+-\s+", name)[1:]).strip()
            if tail:
                add(tail)
                add(re.sub(r"\bsector\b", "sec", tail, flags=re.I))
                add(re.sub(r"\bblock\b", "blk", tail, flags=re.I))

    # Word-drop: "Gulistan-e-Jauhar" -> jauhar ; "DHA Defence" -> defence ;
    # "Bahria Town Karachi" -> bahria / bahria town.
    words = [w for w in re.sub(r"\be\b", " ", norm(name)).split() if w]
    if len(words) > 1:
        for w in words:
            if len(w) >= 4 and w not in GENERIC:
                add(w)
        add(" ".join(words[:-1]))
        add(" ".join(words[1:]))

    return out


def _abbr_aliases(node: dict) -> set[str]:
    out: set[str] = set()
    words = norm(node["name"]).split()
    for i, w in enumerate(words):
        for ab in ABBR.get(w, []):
            variant = words.copy()
            variant[i] = ab
            out.add(" ".join(variant))
    return out


def build_aliases(nodes: dict[int, dict]) -> list[tuple[str, int, str]]:
    """-> [(alias_norm, location_id, source)] with both guards applied."""
    canonical = {norm(n["name"]): n["id"] for n in nodes.values()}
    rows: list[tuple[str, int, str]] = []
    seen: set[tuple[str, int]] = set()

    for node in nodes.values():
        for source, aliases in (
            ("rule", _rule_aliases(node, nodes)),
            ("abbr", _abbr_aliases(node)),
        ):
            for alias in aliases:
                # guard 2: an alias must never equal a DIFFERENT node's name,
                # or "Bahria Town Karachi" would claim "karachi" (node 2).
                owner = canonical.get(alias)
                if owner is not None and owner != node["id"]:
                    continue
                key = (alias, node["id"])
                if key in seen:
                    continue
                seen.add(key)
                rows.append((alias, node["id"], source))
    return rows
